import type {
  AccountabilityLink,
  NotificationSettings,
  Rule,
  StudentSummary,
  Trade,
  User,
} from '@/types'
import { uid } from './utils'

export const DEFAULT_RULES: Rule[] = [
  {
    id: 'rule_max_trades',
    name: 'Max Trades Per Day',
    type: 'MAX_TRADES_PER_DAY',
    value: 3,
    unit: 'trades',
    enabled: true,
    enforcement: 'OVERLAY',
    category: 'session',
    description: 'Hard cap on trade count per 24h session.',
  },
  {
    id: 'rule_max_daily_loss',
    name: 'Max Daily Loss',
    type: 'MAX_DAILY_LOSS',
    value: 300,
    unit: 'USD',
    enabled: true,
    enforcement: 'LOCK',
    category: 'loss',
    description: 'If losses exceed this, session is locked.',
  },
  {
    id: 'rule_max_risk',
    name: 'Max Risk Per Trade',
    type: 'MAX_RISK_PER_TRADE',
    value: 1,
    unit: '% account',
    enabled: true,
    enforcement: 'WARNING',
    category: 'position',
    description: 'Risk cap per single position.',
  },
  {
    id: 'rule_max_lot',
    name: 'Max Lot Size',
    type: 'MAX_LOT_SIZE',
    value: 1.0,
    unit: 'lots',
    enabled: true,
    enforcement: 'FRICTION',
    category: 'position',
    description: 'Upper bound on position size.',
  },
  {
    id: 'rule_loss_streak',
    name: 'Max Consecutive Losses',
    type: 'MAX_CONSECUTIVE_LOSSES',
    value: 2,
    unit: 'losses',
    enabled: true,
    enforcement: 'COOLDOWN',
    category: 'loss',
    description: 'Cool off after a losing streak.',
  },
  {
    id: 'rule_cooldown_after_loss',
    name: 'Cooldown After Loss',
    type: 'COOLDOWN_AFTER_LOSS',
    value: 5,
    unit: 'minutes',
    enabled: true,
    enforcement: 'COOLDOWN',
    category: 'behavior',
    description: 'Minimum wait between trades after a loss.',
  },
  {
    id: 'rule_no_revenge',
    name: 'No Revenge Trading',
    type: 'NO_REVENGE_TRADING',
    value: 1,
    enabled: true,
    enforcement: 'OVERLAY',
    category: 'behavior',
    description: 'Detect and block size escalation after a loss.',
  },
  {
    id: 'rule_max_drawdown',
    name: 'Max Daily Drawdown',
    type: 'MAX_DAILY_DRAWDOWN',
    value: 500,
    unit: 'USD',
    enabled: true,
    enforcement: 'LOCK',
    category: 'loss',
    description: 'Hard session-lock threshold.',
  },
]

export const SEED_TRADES: Trade[] = [
  {
    id: uid(),
    pair: 'EUR/USD',
    direction: 'LONG',
    entryPrice: 1.0842,
    exitPrice: 1.0867,
    stopLoss: 1.0825,
    takeProfit: 1.087,
    lotSize: 0.5,
    session: 'LONDON',
    result: 'WIN',
    pnl: 125.0,
    emotion: 'CONFIDENT',
    note: 'Clean breakout off london open.',
    ruleViolations: [],
    openedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 2.6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uid(),
    pair: 'XAU/USD',
    direction: 'SHORT',
    entryPrice: 2342.1,
    exitPrice: 2346.2,
    stopLoss: 2348.0,
    takeProfit: 2334.0,
    lotSize: 0.2,
    session: 'NY',
    result: 'LOSS',
    pnl: -82.0,
    emotion: 'NEUTRAL',
    note: 'Setup valid, price just pushed through.',
    ruleViolations: [],
    openedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 1.7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: uid(),
    pair: 'GBP/JPY',
    direction: 'LONG',
    entryPrice: 199.15,
    exitPrice: 199.62,
    stopLoss: 198.9,
    takeProfit: 199.75,
    lotSize: 0.3,
    session: 'NY',
    result: 'WIN',
    pnl: 87.5,
    emotion: 'CONFIDENT',
    note: 'Retest of prior high, clean entry.',
    ruleViolations: [],
    openedAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
]

export const DEFAULT_USER: User = {
  id: 'user_demo',
  email: 'trader@trepid.app',
  name: 'Demo Trader',
  role: 'TRADER',
  createdAt: new Date().toISOString(),
}

export const PAIRS = [
  'EUR/USD',
  'GBP/USD',
  'USD/JPY',
  'USD/CHF',
  'AUD/USD',
  'NZD/USD',
  'USD/CAD',
  'EUR/GBP',
  'EUR/JPY',
  'GBP/JPY',
  'XAU/USD',
  'XAG/USD',
  'BTC/USD',
  'ETH/USD',
  'US30',
  'NAS100',
  'SPX500',
]

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  inApp: true,
  push: false,
  sms: false,
  smsPhone: '',
  notifyStage: 5,
  dailySummary: true,
  morningPriming: true,
}

export const SEED_PARTNERS: AccountabilityLink[] = [
  {
    id: 'partner_mentor_1',
    partnerEmail: 'coach@edgefund.io',
    partnerName: 'Nikolai R.',
    role: 'MENTOR',
    status: 'ACTIVE',
    permissions: {
      viewScore: true,
      viewViolations: true,
      viewTradeCount: true,
      viewPnl: false,
      receiveAlerts: true,
    },
    createdAt: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    lastNotifiedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    lastAlertReason: 'Max daily loss exceeded — session locked.',
  },
  {
    id: 'partner_friend_1',
    partnerEmail: 'avery@deskmate.io',
    partnerName: 'Avery K.',
    role: 'PARTNER',
    status: 'ACTIVE',
    permissions: {
      viewScore: true,
      viewViolations: true,
      viewTradeCount: true,
      viewPnl: false,
      receiveAlerts: false,
    },
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'partner_pending_1',
    partnerEmail: 'rhea@propfund.com',
    partnerName: 'Rhea V.',
    role: 'MENTOR',
    status: 'PENDING',
    permissions: {
      viewScore: true,
      viewViolations: true,
      viewTradeCount: true,
      viewPnl: true,
      receiveAlerts: true,
    },
    createdAt: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
  },
]

export const MOCK_STUDENTS: StudentSummary[] = [
  {
    id: 'stu_1',
    name: 'Marcus Wen',
    email: 'marcus@trader.co',
    disciplineScore: 92,
    tradesToday: 2,
    maxTrades: 5,
    violations: 0,
    lossStreak: 0,
    enforcementLevel: 0,
    status: 'DISCIPLINED',
  },
  {
    id: 'stu_2',
    name: 'Sofia Ortega',
    email: 'sofia@trader.co',
    disciplineScore: 78,
    tradesToday: 4,
    maxTrades: 5,
    violations: 1,
    lossStreak: 1,
    enforcementLevel: 1,
    status: 'DISCIPLINED',
    lastAlertAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    recentViolation: 'Entry too close to news event',
  },
  {
    id: 'stu_3',
    name: 'Jason Hale',
    email: 'jason@trader.co',
    disciplineScore: 54,
    tradesToday: 6,
    maxTrades: 5,
    violations: 3,
    lossStreak: 2,
    enforcementLevel: 3,
    status: 'AT_RISK',
    lastAlertAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    recentViolation: 'Max daily trades exceeded — cooldown active',
  },
  {
    id: 'stu_4',
    name: 'Priya Shah',
    email: 'priya@trader.co',
    disciplineScore: 28,
    tradesToday: 9,
    maxTrades: 5,
    violations: 5,
    lossStreak: 3,
    enforcementLevel: 5,
    status: 'CRITICAL',
    lastAlertAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    recentViolation: 'Session locked — revenge trading pattern detected',
  },
  {
    id: 'stu_5',
    name: 'Thomas Liu',
    email: 'thomas@trader.co',
    disciplineScore: 88,
    tradesToday: 3,
    maxTrades: 5,
    violations: 0,
    lossStreak: 0,
    enforcementLevel: 0,
    status: 'DISCIPLINED',
  },
  {
    id: 'stu_6',
    name: 'Olivia Grant',
    email: 'olivia@trader.co',
    disciplineScore: 66,
    tradesToday: 5,
    maxTrades: 5,
    violations: 1,
    lossStreak: 2,
    enforcementLevel: 2,
    status: 'AT_RISK',
    recentViolation: 'Loss streak — friction gate triggered',
  },
]

export const PRESETS = [
  {
    id: 'preset_conservative',
    name: 'Conservative Trader',
    description: 'Tight rules, low risk, long-term edge.',
    overrides: {
      MAX_TRADES_PER_DAY: 3,
      MAX_DAILY_LOSS: 200,
      MAX_RISK_PER_TRADE: 0.5,
      MAX_LOT_SIZE: 0.5,
      MAX_CONSECUTIVE_LOSSES: 2,
      COOLDOWN_AFTER_LOSS: 10,
      MAX_DAILY_DRAWDOWN: 300,
    },
  },
  {
    id: 'preset_ftmo',
    name: 'Prop Firm Challenge',
    description: 'FTMO-style drawdown limits.',
    overrides: {
      MAX_TRADES_PER_DAY: 5,
      MAX_DAILY_LOSS: 500,
      MAX_RISK_PER_TRADE: 1,
      MAX_LOT_SIZE: 1,
      MAX_CONSECUTIVE_LOSSES: 3,
      COOLDOWN_AFTER_LOSS: 5,
      MAX_DAILY_DRAWDOWN: 500,
    },
  },
  {
    id: 'preset_scalper',
    name: 'Aggressive Scalper',
    description: 'High frequency with tight stops.',
    overrides: {
      MAX_TRADES_PER_DAY: 15,
      MAX_DAILY_LOSS: 600,
      MAX_RISK_PER_TRADE: 0.5,
      MAX_LOT_SIZE: 1,
      MAX_CONSECUTIVE_LOSSES: 3,
      COOLDOWN_AFTER_LOSS: 2,
      MAX_DAILY_DRAWDOWN: 800,
    },
  },
  {
    id: 'preset_new',
    name: 'New Trader',
    description: 'Strict training wheels.',
    overrides: {
      MAX_TRADES_PER_DAY: 2,
      MAX_DAILY_LOSS: 100,
      MAX_RISK_PER_TRADE: 0.25,
      MAX_LOT_SIZE: 0.1,
      MAX_CONSECUTIVE_LOSSES: 1,
      COOLDOWN_AFTER_LOSS: 30,
      MAX_DAILY_DRAWDOWN: 150,
    },
  },
]
